Add CI and stuff
gesundheitscloud/donut pull request #1
Opened 2021-07-19 08:39 UTC by weese

2021-07-19 12:58 UTC, LRueckert requested changes

2021-07-19 12:58 UTC, LRueckert commented on jenkinsfile/build.groovy
> +    autodeployTenants: 'd4l rki',
this is single tenant

2021-07-19 12:58 UTC, LRueckert commented on jenkinsfile/deploy.groovy
> +    useTenantSpecificVault: true // required only for VE-multitenancy
this is single tenant

2021-07-19 14:57 UTC, weese commented
The ingress must always be deployed, as we don’t use lagrange but the ingress for the app and backend.

2021-07-20 07:45 UTC, LRueckert approved these changes

2021-07-20 08:01 UTC, merged